#!/usr/bin/bash

set -euo pipefail

cd `dirname $0`

case "$1" in
  bootstrap)
    ./Build unmount
    sudo rm -rf _root
    sudo rm -rf /opt/qrpc/pkg
    sudo apt-get update --allow-releaseinfo-change
    sudo apt-get install -y debootstrap patch bindfs
    sudo debootstrap --variant=minbase jammy _root http://archive.ubuntu.com/ubuntu/
    sudo chmod 700 _root
    sudo bash -c 'echo nameserver 8.8.8.8 >> _root/etc/resolv.conf'
    sudo git clone --depth 1 https://github.com/NetBSD/pkgsrc.git _root/root/pkgsrc
    sudo patch _root/root/pkgsrc/mk/defaults/mk.conf < config/mk.conf.patch
    sudo bash -c 'echo >> _root/etc/bash.bashrc'
    sudo bash -c 'echo '"'"'export PATH=/opt/qrpc/pkg/bin:$PATH'"'"' >> _root/etc/bash.bashrc'
    sudo bash -c 'echo '"'"'export MANPATH=/opt/qrpc/pkg/man:$MANPATH'"'"' >> _root/etc/bash.bashrc'
    sudo chroot _root /usr/bin/apt-get update
    sudo chroot _root /usr/bin/apt-get install -y gcc g++ wget
    ./Build mount
    sudo chroot _root /usr/bin/bash -ilc 'cd /root/pkgsrc/bootstrap && ./bootstrap --prefix /opt/qrpc/pkg --pkgdbdir /opt/qrpc/pkg/pkgdb --sysconfdir /opt/qrpc/pkg/etc --varbase /opt/qrpc/var'
    ;;
  unmount)
    if sudo mountpoint -q _pkgsrc; then
      sudo umount _pkgsrc || sudo umount -l _pkgsrc || true
    fi
    if sudo mountpoint -q _root/opt/qrpc; then
      sudo umount _root/opt/qrpc || sudo umount -l _root/opt/qrpc || true
    fi
    ;;
  mount)
    if ! sudo mountpoint -q _root/opt/qrpc; then
      sudo mkdir -p /opt/qrpc
      sudo mkdir -p _root/opt/qrpc
      sudo mount --bind /opt/qrpc _root/opt/qrpc
    fi
    if ! sudo mountpoint -q _pkgsrc; then
      MAIN_USER=$USER;
      sudo mkdir -p _root/root/pkgsrc
      mkdir -p _pkgsrc
      sudo bindfs --map=root/$MAIN_USER:@root/@$MAIN_USER _root/root/pkgsrc _pkgsrc
    fi
    ;;
  devel)
    ./Build mount
    rsync -a meta-pkgs _pkgsrc/
    cd _pkgsrc
      git stash && git pull && git stash pop
    cd ..
    sudo chroot _root /usr/bin/bash -ilc 'cd /root/pkgsrc/meta-pkgs/qrpc-devel && bmake update'
    ;;
  root)
    sudo chroot _root /usr/bin/bash
    ;;
  clean)
    export PATH=/opt/qrpc/pkg/bin:$PATH
    rebar3 clean
    ;;
  build)
    export PATH=/opt/qrpc/pkg/bin:$PATH
    rebar3 compile
    ;;
  check)
    export PATH=/opt/qrpc/pkg/bin:$PATH
    rebar3 eunit && rebar3 ct --verbose && rebar3 cover && echo ALL_TEST_PASS
    ;;
  shell)
    export PATH=/opt/qrpc/pkg/bin:$PATH
    rebar3 shell
    ;;
  package)
    export PATH=/opt/qrpc/pkg/bin:$PATH
    rm -rf _pkgsrc/packages/qrpc-prod
    mkdir -p _pkgsrc/packages/qrpc-prod
    sudo chroot _root /usr/bin/bash -ilc 'cd /root/pkgsrc/meta-pkgs/qrpc-prod && bmake update'
    sudo chroot _root /opt/qrpc/pkg/bin/pkg_tarup -d /root/pkgsrc/packages/qrpc-prod -a qrpc-prod
    sudo chroot _root cp -p /opt/qrpc/pkg/sbin/pkg_add /root/pkgsrc/packages/qrpc-prod/.
    rebar3 as prod tar
    prod=$(ls -t _build/prod/rel/qrpc/*.tar.gz | head -1)
    mv "$prod" _pkgsrc/packages/qrpc-prod/qrpc.tgz
    cp config/pkgrc _pkgsrc/packages/qrpc-prod/.pkgrc
    cp config/foreground.sh _pkgsrc/packages/qrpc-prod/foreground.sh
    cp config/qrpc.service _pkgsrc/packages/qrpc-prod/qrpc.service
    ./scripts/license_collector.sh gather _pkgsrc/packages/qrpc-prod qrpc.tgz
    echo '#!/bin/bash
        set -euo pipefail
        cd $(dirname $0)
        . .pkgrc
    ' > _pkgsrc/packages/qrpc-prod/install.sh
    chmod +x _pkgsrc/packages/qrpc-prod/install.sh
    name="$(basename "${prod%.tar.gz}")-$(rustc -Vv | sed -n 's/^host: //p')"
    mkdir -p _release_packages
    mv _pkgsrc/packages/qrpc-prod "_release_packages/${name}"
    cd _release_packages
    tar -zcf "${name}.tar.gz" "$name"
    rm -rf latest
    mv "$name" latest
    cd ..
    echo "_release_packages/${name}.tar.gz"
    ;;
  install)
    export PATH=/opt/qrpc/pkg/bin:$PATH
    ./Build package
    sudo _release_packages/latest/install.sh
    ;;
  release)
    export PATH=/opt/qrpc/pkg/bin:$PATH
    rebar3 as prod release
    ;;
  *)
    echo "this is a help message"
    ;;
esac
