DISTNAME=       qrpc-devel-0.1.0
CATEGORIES=     meta-pkgs www
MASTER_SITES=   # empty

MAINTAINER=     qrpc@su-shiki.com
COMMENT=        All you need to build qrpc

DEPENDS+=       qrpc-prod>=0.1.0:../../meta-pkgs/qrpc-prod
DEPENDS+=       rebar3>=3.24.0:../../devel/rebar3

META_PACKAGE=   yes

.include "../../mk/bsd.pkg.mk"
