DISTNAME=       qrpc-prod-0.1.0
CATEGORIES=     meta-pkgs www
MASTER_SITES=   # empty

MAINTAINER=     qrpc@su-shiki.com
COMMENT=        All you need to run qrpc as prod

DEPENDS+=       cronolog>=1.6.2:../../www/cronolog

META_PACKAGE=   yes

.include "../../mk/bsd.pkg.mk"
